---
- name: Setup Infrastructure for Yii2 Application
  hosts: ec2_servers
  become: true
  vars:
    docker_compose_version: "2.21.0"
    nginx_conf_source: "../nginx/yii2-app.conf"
    nginx_conf_dest: "/etc/nginx/sites-available/yii2-app"
    app_user: "ubuntu"
    app_directory: "/home/{{ app_user }}/yii2-app"

  tasks:
    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: "0644"

    - name: Add Docker GPG key to keyring
      shell: gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository with signed-by
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
